version: '3'
services:
  alexa-tts:
    container_name: alexa-tts
    image: dev96pad/alexa-tts:latest
    build: .
    restart: always
    volumes:
      - ${ALEXA_TTS_SECRETS}:/var/data/secrets/alexa-tts
    networks:
      - jenkins
networks:
  jenkins:
    external: true