version: '3'
services:
  alexa-tts:
    container_name: alexa-tts
    image: dev96pad/alexa-tts:latest
    build: .
    restart: always
    volumes:
      - alexa-tts-secrets:/var/data/secrets/alexa-tts
    networks:
      - jenkins
volumes:
  alexa-tts-secrets:
    external: true
networks:
  jenkins:
    external: true